### ISSUE TITLE
File already exists error

### ISSUE THREAD

**Issue by psamim** [al1b/KTOP#7]
Hi,

If the output file exists, ktop silently fails. This is the error log:

```
The file '/home/samim/Calibre Library/bhaallh/ayqan (41)/ayqan - bhaallh.epub' already exists.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo[TSafeHandle](TSafeHandle handle, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.DoCreateFromDirectory(String sourceDirectoryName, String destinationArchiveFileName, Nullable`1 compressionLevel, Boolean includeBaseDirectory, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.CreateFromDirectory(String sourceDirectoryName, String destinationArchiveFileName, CompressionLevel compressionLevel, Boolean includeBaseDirectory)
   at KTOP.EBookReader.EPubReader.SaveAs(String path) in /tmp/yaourt-tmp-samim/aur-ktop-git/src/KTOP/src/KTOP.EBookReader/EpubReader.cs:line 104
   at KTOP.CLI.Program.<>c__DisplayClass1_0.<CreateCommandLineInterface>b__0() in /tmp/yaourt-tmp-samim/aur-ktop-git/src/KTOP/src/KTOP.CLI/Program.cs:line 77
```

I suggest printing the error in the terminal or more preferably having an option to overwrite the file.

Thanks,
Samim

**Comment by al1b** [comment]
@psamim 

Changes:

1. If input and output file are the same, *KTOP* will create a backup file and overwrite the original file.
2. Added `-r|--overwrite` option ( will overwrite the file without user prompt )
3. If output file exists user will decide to cancel the operation or overwrite the file via an user prompt.

**Comment by psamim** [comment]
@al1b Thanks! great.
